version: v2
global:
  runner:
    os_image: ubuntu
  variables:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    steps:
    - commands:
      - pyenv install --list  # List all available Python versions
      - pyenv install 3.10.5  # Install Python 3.10.5
      - pyenv global 3.10.5   # Set Python 3.10.5 as the global version
      - python --version      # Verify the Python version
    - run: pip install telebot flask pymongo aiohttp python-telegram-bot  # Install dependencies
    - commands:
      - chmod +x xxxx  # Set execute permission
      - python titan.py  # Run the Python script
