# spec version (v1/v2)
version: v2
global: 
  runner:
    os_image: ubuntu # Use Ubuntu Linux as the OS
  variables: 
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    steps:
    - commands:
      - pyenv global 3.10.5  # set Python version
      - python --version  # verify version
      - pip install telebot flask pymongo aiohttp python-telegram-bot
      - chmod +x xxxx
      - python titan.py

