version: v2
global:
  runner:
    os_image: ubuntu
  variables:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    steps:
    - commands:
      - pyenv install 3.10.5  # Install Python 3.10.5
      - pyenv global 3.10.5   # Set Python 3.10.5 as the global version
      - python --version      # Verify Python version
      - pip install telebot flask pymongo aiohttp python-telegram-bot  # Install dependencies

    - commands:
      - git clone https://github.com/paidbotXtitan01/new.git  # Clone your GitHub repo
      - cd new  # Change to the cloned directory
      - chmod +x main.py  # Make the script executable
      - python main.py  # Run the script
